export const AGREGAR_PUBLICACION = 'AGREGAR_PUBLICACION';
export const AGREGAR_PUBLICACION_EXITO = 'AGREGAR_PUBLICACION_EXITO';
export const AGREGAR_PUBLICACION_ERROR = 'AGREGAR_PUBLICACION_ERROR';

export const COMENZAR_DESCARGA_PUBLICACIONES = 'COMENZAR_DESCARGA_PUBLICACIONES';
export const DESCARGAR_PUBLICACIONES_EXITO = 'DESCARGAR_PUBLICACIONES_EXITO';
export const DESCARGAR_PUBLICACIONES_ERROR = 'DESCARGAR_PUBLICACIONES_ERROR';

export const OBTENER_PUBLICACION = 'OBTENER_PUBLICACION';
export const PUBLICACION_OBTENIDA_EXITO = 'PUBLICACION_OBTENIDA_EXITO';
export const PUBLICACION_OBTENIDA_ERROR = 'PUBLICACION_OBTENIDA_ERROR';

export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
export const CREATE_CATEGORIA = "CREATE_CATEGORIA";
